# .github/workflows/main.yml
name: 翻译并部署维基页面

on:
  schedule:
    - cron: '0 4 * * *' # 每天北京时间中午12点运行
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: 检出仓库代码 (主分支)
        uses: actions/checkout@v4

      # ... (setup-node, apt-get install rsync, yarn install, puppeteer download, etc.)

      - name: 运行翻译脚本
        run: node translate.js

      - name: 提交更新后的状态文件
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ci: 更新页面状态记录"
          # 注意：我们不需要提交 deleted-files.txt，因为它是一次性的
          file_pattern: |
            last_edit_info.json
            redirect_map.json
          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
          commit_options: '--no-verify'
      
      # --- 新的、更安全的部署逻辑 ---

      - name: 检出 gh-pages 分支到单独目录
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages-dir

      - name: 从 gh-pages 中删除源站已不存在的页面
        run: |
          # 检查删除记录文件是否存在
          if [ -f deleted-files.txt ]; then
            echo "发现需要删除的文件列表，正在处理..."
            # 切换到 gh-pages-dir 目录，然后根据列表删除文件
            # 使用 xargs 可以安全地处理文件名中可能包含的空格等特殊字符
            cd gh-pages-dir && cat ../deleted-files.txt | xargs -r rm -f
          else
            echo "没有需要删除的文件。"
          fi

      - name: 将新构建的文件增量更新到部署目录
        run: |
          # 使用 rsync 将 output 目录的内容合并到 gh-pages-dir
          # -a: 归档模式
          # -v: 显示详细过程
          # 这里没有 --delete，所以它只会添加和更新，不会删除
          rsync -av ./output/ ./gh-pages-dir/

      - name: 部署到 GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gh-pages-dir
          # 保持 true，因为我们已经手动完成了所有文件操作
          keep_files: true
