# .github/workflows/main.yml
name: 翻译并部署维基页面

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: 检出仓库代码
        uses: actions/checkout@v4

      - name: 设置 Node.js 环境
        uses: actions/setup-node@v4
        with:
          # 关键修改：将 Node.js 版本从 18 升级到 20
          node-version: '20'
          # 我们仍然不使用缓存，以确保环境的纯净
          # cache: 'yarn' # 保持删除状态

      - name: 安装系统依赖
        run: |
          sudo apt-get update
          sudo apt-get install -yq \
            ca-certificates fonts-liberation libasound2t64 libatk-bridge2.0-0 libatk1.0-0 \
            libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 \
            libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 \
            libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 \
            libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 \
            libxi6 libxrandr2 libxrender1 libxss1 libxtst6 lsb-release wget xdg-utils

      - name: 安装 Node.js 依赖 (使用 Yarn)
        env:
          PUPPETEER_SKIP_DOWNLOAD: 'true'
        run: yarn install

      - name: 单独下载 Chromium 浏览器
        run: npx puppeteer browsers install chrome

      - name: 运行翻译脚本
        run: node translate.js

      - name: 部署到 GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
